/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Axelandre' at '10/04/17 16:41' with Gradle 2.13
 *
 * @author Axelandre, @date 10/04/17 16:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
